routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::resource('posts','post');
Route::get('preview','post@preview');
Route::get('posts/delete/{id}','post@destroy');

app/Posts.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Posts extends Model
{
    
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/post.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Posts;

class post extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $publish  = Posts::where('status','publish')->get();
        $draft  = Posts::where('status','draft')->get();
        $trash  = Posts::where('status','trash')->get();
        return view('posts/index',compact('publish','draft','trash'));
    }

    public function preview()
    {
        $data  = Posts::where('status','publish')->paginate(6);
        return view('posts/preview',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $posts = new Posts();
        $posts->title = $request->title;
        $posts->content = $request->content;
        $posts->category = $request->category;
        $posts->status = $request->status;
        $posts->save();
      
        return redirect('posts');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Posts::find($id);
        return view('posts/edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $posts = Posts::find($id);
        $posts->title = $request->title;
        $posts->content = $request->content;
        $posts->category = $request->category;
        $posts->status = $request->status;
        $posts->save();
      
        return redirect('posts');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $posts = Posts::find($id);
        $posts->status = "trash";
        $posts->save();
      
        return redirect('posts');
    }

}

resources/views/index.blade.php
@extends('layout/layout')
@section('title','Halaman Beranda')
@section('content')

    <div class="row">
    <div class="col-12"><br></div>
    <div class="col-12"><br></div>
    <div class="col-12"><br></div>
    <div class="col-12"><br></div>
    <div class="col-12"><br></div>
    <div class="col-12"><br></div>
        <div class="col-12 text-center">
            <h4>Welcome To My Test</h4>
        </div>
    </div>

@endsection

resources/views/layout/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title')</title>
    <!-- Data Table -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
    <!-- Bootstrap CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <section class="header">
        <div class="container bg-dark">
            <nav class="navbar navbar-expand-lg">
                <div class="container-fluid">
                    <a class="navbar-brand text-light" href="{{url('/')}}">TEST</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon text-light"></span>
                        </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active text-light" aria-current="page" href="{{url('/')}}">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Posts
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{{url('posts')}}">All Posts</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{{route('posts.create')}}">Add Posts</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{{url('preview')}}">Preview</a></li>
                        </ul>
                        </li>
                    </ul>
                    </div>
                </div>
            </nav>    
        </div>
    </section>

    <br>

    <section class="main">
        <div class="container">
            @yield('content')
        </div>
    </section>

    <section class="footer fixed-bottom">
        <div class="container bg-dark">
            <div class="row">
                <div class="col-4"></div>
                <div class="col-4 text-center text-light"><br>&copy; Copyright Fatih Putera <?= date('Y') ?><br><br></div>
                <div class="col-4"></div>
            </div>
        </div>
    </section>

    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <!-- Data Table -->
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    
    <script>
        $(document).ready( function () {
            $('.myTable').DataTable();
        } );
    </script>
</body>
</html>

resources/views/posts/create.blade.php
@extends('layout/layout')
@section('title','Create Posts')
@section('content')

    <div class="row">
        <div class="col-md-12 d-flex justify-content-center">
            <div class="card">
                <div class="card-header">
                    Create Post
                </div>
                <div class="card-body">
                    <form method="post" action="{{route('posts.store')}}">
                    @csrf
                        <div class="mb-3">
                            <label for="title" class="form-label">Title</label>
                            <input type="text" class="form-control" id="title" name="title" required>
                        </div>
                        <div class="mb-3">
                            <label for="content" class="form-label">Content</label>
                            <textarea name="content" id="content" cols="50" rows="10" class="form-control" required></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="category" class="form-label">Category</label>
                            <input type="text" class="form-control" id="category" name="category" required>
                        </div>
                        <div class="mb-3">
                            <label for="status" class="form-label">Status</label> <br>
                            <input type="radio" id="status" name="status" required value="publish"> Publish
                            <input type="radio" id="status" name="status" value="draft"> Draft
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/posts/edit.blade.php
@extends('layout/layout')
@section('title','Edit Posts')
@section('content')

    <div class="row">
        <div class="col-md-12 d-flex justify-content-center">
            <div class="card">
                <div class="card-header">
                    Edit Post
                </div>
                <div class="card-body">
                    <form method="post" action="{{route('posts.update',$data->id)}}">
                    @METHOD('PUT')
                    @csrf
                        <div class="mb-3">
                            <label for="title" class="form-label">Title</label>
                            <input type="text" class="form-control" id="title" name="title" required value="{{$data->title}}">
                        </div>
                        <div class="mb-3">
                            <label for="content" class="form-label">Content</label>
                            <textarea name="content" id="content" cols="50" rows="10" class="form-control" required>{{$data->content}}</textarea>
                        </div>
                        <div class="mb-3">
                            <label for="category" class="form-label">Category</label>
                            <input type="text" class="form-control" id="category" name="category" required value="{{$data->category}}">
                        </div>
                        <div class="mb-3">
                            <label for="status" class="form-label">Status</label> <br>
                            <input type="radio" id="status" name="status" required value="publish" <?php if($data->status == 'publish'){ echo "checked"; } ?>> Publish
                            <input type="radio" id="status" name="status" value="draft" <?php if($data->status == 'draft'){ echo "checked"; } ?>> Draft
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/posts/index.blade.php
@extends('layout/layout')
@section('title','Posts')
@section('content')

    <div class="row">
        <div class="col-md-12 d-flex justify-content-center">
            <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Published ({{count($publish)}})</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Drafts ({{count($draft)}})</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">Trashed ({{count($trash)}})</button>
                </li>
            </ul>
        </div>
        <div class="col-md-12 d-flex justify-content-center"><br></div>
        <div class="col-md-12 d-flex justify-content-center">
            <div class="tab-content" id="pills-tabContent">
                <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
                    <table class="table myTable">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Title</th>
                                <th>category</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $no = 1; ?>
                            @foreach($publish as $row)
                            <tr>
                                <td>{{$no++}}</td>
                                <td>{{$row->title}}</td>
                                <td>{{$row->category}}</td>
                                <td>
                                    <a href="{{route('posts.edit',$row->id)}}" class="btn btn-warning"><i class="fa fa-pencil"></i></a>
                                    <a href="{{url('posts/delete/'.$row->id)}}" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-12 d-flex justify-content-center">
            <div class="tab-content" id="pills-tabContent">
                <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
                    <table class="table myTable">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Title</th>
                                <th>category</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $no = 1; ?>
                            @foreach($draft as $row)
                            <tr>
                                <td>{{$no++}}</td>
                                <td>{{$row->title}}</td>
                                <td>{{$row->category}}</td>
                                <td>
                                    <a href="{{route('posts.edit',$row->id)}}" class="btn btn-warning"><i class="fa fa-pencil"></i></a>
                                    <a href="{{url('posts/delete/'.$row->id)}}" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-12 d-flex justify-content-center">
            <div class="tab-content" id="pills-tabContent">
                <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
                    <table class="table myTable">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Title</th>
                                <th>category</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $no = 1; ?>
                            @foreach($trash as $row)
                            <tr>
                                <td>{{$no++}}</td>
                                <td>{{$row->title}}</td>
                                <td>{{$row->category}}</td>
                                <td>
                                    <a href="{{route('posts.edit',$row->id)}}" class="btn btn-warning"><i class="fa fa-pencil"></i></a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    

@endsection

resources/views/posts/preview.blade.php
@extends('layout/layout')
@section('title','Preview')
@section('content')

    <div class="row">
        <?php $no = 1; ?>
        @foreach($data as $row)
            <?php $no++; ?>
            @if($no == 5)
            <div class="col-md-12 d-flex justify-content-center"><br></div>
            <div class="col-md-4 d-flex justify-content-center">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{$row->title}}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{$row->category}}</h6>
                        <p class="card-text">{{$row->content}}</p>
                    </div>
                </div>
            </div>
            @else
            <div class="col-md-4 d-flex justify-content-center">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{$row->title}}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{$row->category}}</h6>
                        <p class="card-text">{{$row->content}}</p>
                    </div>
                </div>
            </div>
            @endif
        @endforeach
        <div class="col-md-12 d-flex justify-content-center"><br><br></div>
        <div class="col-md-3 d-flex justify-content-center">
            Halaman : {{ $data->currentPage() }} 
        </div>
        <div class="col-md-3 d-flex justify-content-center">
            Jumlah Data : {{ $data->total() }} 
        </div>
        <div class="col-md-3 d-flex justify-content-center">
            Data Per Halaman : {{ $data->perPage() }} 
        </div>
        <div class="col-md-3 d-flex justify-content-center">
            {{ $data->links() }}
        </div>
    </div>


@endsection